// Generated by LiveScript 1.4.0
(function(){
  var philtre, readStdinAsLinesThen, noEmpty, philtreFromStdin;
  philtre = require("./philtre").philtre;
  readStdinAsLinesThen = function(func){
    var buf;
    buf = '';
    process.stdin.setEncoding('utf-8');
    process.stdin.on('data', function(it){
      return buf += it;
    });
    return process.stdin.on('end', function(){
      return func(noEmpty(
      buf.split("\n")));
    });
  };
  noEmpty = function(it){
    return it.filter(function(it){
      return !(it === null || it === '');
    });
  };
  philtreFromStdin = function(){
    return readStdinAsLinesThen(function(it){
      var query, objects;
      query = process.argv.slice(2).join(' ');
      objects = it.map(JSON.parse);
      return philtre(query, objects).map(function(it){
        return console.log(JSON.stringify(it));
      });
    });
  };
  philtreFromStdin();
}).call(this);
